/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author leang
 */
public class ComprarPalco extends javax.swing.JPanel {

    /**
     * Creates new form ComprarPalco
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
    public ComprarPalco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelCedula = new javax.swing.JLabel();
        txtCedulaCompraPalco = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtEmailCompraPalco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTelefonoCompraPalco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNombreCompraPalco = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtCodigoCompraPalco = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        btnComprarPalco = new javax.swing.JButton();
        btnVerPalcos = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Comprar Palco");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel1)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        labelCedula.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        labelCedula.setText("Cédula");
        jPanel1.add(labelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtCedulaCompraPalco.setBorder(null);
        txtCedulaCompraPalco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaCompraPalcoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedulaCompraPalco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 180, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 210, 20));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txtEmailCompraPalco.setBorder(null);
        txtEmailCompraPalco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailCompraPalcoActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmailCompraPalco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 180, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel10.setText("Telefono");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        txtTelefonoCompraPalco.setBorder(null);
        txtTelefonoCompraPalco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoCompraPalcoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefonoCompraPalco, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 140, -1));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel11.setText("Nombre Completo");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        txtNombreCompraPalco.setBorder(null);
        txtNombreCompraPalco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCompraPalcoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreCompraPalco, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 200, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 180, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 180, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 210, 20));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel12.setText("Código de palco");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txtCodigoCompraPalco.setBorder(null);
        txtCodigoCompraPalco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCompraPalcoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigoCompraPalco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 180, 20));

        btnComprarPalco.setBackground(new java.awt.Color(204, 255, 255));
        btnComprarPalco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnComprarPalco.setText("COMPRAR");
        btnComprarPalco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarPalcoActionPerformed(evt);
            }
        });
        jPanel1.add(btnComprarPalco, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 120, 50));

        btnVerPalcos.setBackground(new java.awt.Color(204, 255, 255));
        btnVerPalcos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerPalcos.setText("VER PALCOS");
        btnVerPalcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPalcosActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerPalcos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaCompraPalcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaCompraPalcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaCompraPalcoActionPerformed

    private void txtEmailCompraPalcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailCompraPalcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailCompraPalcoActionPerformed

    private void txtTelefonoCompraPalcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoCompraPalcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoCompraPalcoActionPerformed

    private void txtNombreCompraPalcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCompraPalcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCompraPalcoActionPerformed

    private void txtCodigoCompraPalcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCompraPalcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCompraPalcoActionPerformed

    private void btnComprarPalcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarPalcoActionPerformed
        String sql = "SELECT * FROM palcos WHERE codigoPalco LIKE ?;";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1, txtCodigoCompraPalco.getText());
            rs = pst.executeQuery();
            
            if(rs.next()){
                String sql2 = "INSERT INTO entradasPalcos (nombre,cedula,email,telefono,codigoPalco,nombrePalco) VALUES (?,?,?,?,?,?);";
                pst = con.prepareStatement(sql2);
                pst.setString(1, txtNombreCompraPalco.getText());
                pst.setString(2, txtCedulaCompraPalco.getText());
                pst.setString(3, txtEmailCompraPalco.getText());
                pst.setString(4, txtTelefonoCompraPalco.getText());
                pst.setString(4, txtCodigoCompraPalco.getText());
                pst.setString(4, txtCodigoCompraPalco.getText());
            
                pst.execute();
                con.close();
                JOptionPane.showMessageDialog(null, "Codigo de palco incorrecto o no disponible.");
            }else{
                JOptionPane.showMessageDialog(null, "Codigo de palco incorrecto o no disponible.");
            }
        }catch(Exception e){
            System.out.println("Codigo de palco incorrecto o no disponible. "+e);
        }
    }//GEN-LAST:event_btnComprarPalcoActionPerformed

    private void btnVerPalcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPalcosActionPerformed
        Palcos palcos = new Palcos();
        palcos.setVisible(true);
    }//GEN-LAST:event_btnVerPalcosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarPalco;
    private javax.swing.JButton btnVerPalcos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JTextField txtCedulaCompraPalco;
    private javax.swing.JTextField txtCodigoCompraPalco;
    private javax.swing.JTextField txtEmailCompraPalco;
    private javax.swing.JTextField txtNombreCompraPalco;
    private javax.swing.JTextField txtTelefonoCompraPalco;
    // End of variables declaration//GEN-END:variables
}
