/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author leang
 */
public class PasarelaPayPal extends javax.swing.JPanel {

    /**
     * Creates new form PasarelaPayPal
     */
    public PasarelaPayPal() {
        initComponents();
    }

    public boolean estado;
    
    public String nombre;
    public String cedula;
    public String email;
    public String telefono;
    public String codigoPalco;
    public String nombrePalco;
    public String codigo;
    public int idPalco;
    public String valor;
    
    public int tipoCompra;
    public String zona;
    
    public void setEstado(boolean est){
        this.estado = est;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtContraseñaPayPal = new javax.swing.JTextField();
        txtCorreoPayPal = new javax.swing.JTextField();
        btnIniciarPayPal = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paypal2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 63, 310, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 20, -1));

        txtValor.setText("Valor");
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Pagar con PayPal");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtContraseñaPayPal.setForeground(new java.awt.Color(102, 102, 102));
        txtContraseñaPayPal.setText("Contraseña");
        txtContraseñaPayPal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraseñaPayPalMousePressed(evt);
            }
        });
        jPanel1.add(txtContraseñaPayPal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, -1));

        txtCorreoPayPal.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreoPayPal.setText("Correo Electronico");
        txtCorreoPayPal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoPayPalMousePressed(evt);
            }
        });
        jPanel1.add(txtCorreoPayPal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 290, -1));

        btnIniciarPayPal.setBackground(new java.awt.Color(51, 153, 255));
        btnIniciarPayPal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIniciarPayPal.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarPayPal.setText("Iniciar Sesion");
        btnIniciarPayPal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarPayPalMouseClicked(evt);
            }
        });
        jPanel1.add(btnIniciarPayPal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoPayPalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoPayPalMousePressed
        txtCorreoPayPal.setText("");
    }//GEN-LAST:event_txtCorreoPayPalMousePressed

    private void txtContraseñaPayPalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaPayPalMousePressed
        txtContraseñaPayPal.setText("");
    }//GEN-LAST:event_txtContraseñaPayPalMousePressed

    private void btnIniciarPayPalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarPayPalMouseClicked
        PayPal ventanaPayPal = new PayPal();
        if(this.tipoCompra==1){ventanaPayPal.recepciónInformacion(nombre, cedula, email, telefono, codigoPalco, nombrePalco, codigo, idPalco, valor);}
        if(this.tipoCompra==2){ventanaPayPal.recepcionInformacionZonas(nombre, cedula, email, telefono, zona, codigo);}
        if(!validarCampos()) JOptionPane.showMessageDialog(null, "Llene todos los campos.");
            
            else{
                if(!validarCorreo(txtCorreoPayPal.getText()))
                            JOptionPane.showMessageDialog(null, "Correo no válido");
                else{
                    btnIniciarPayPal.setText("Iniciando ...");
                    try {
                        
                        Thread.sleep(2*1000);
                        ventanaPayPal.setVisible(true);  
                        btnIniciarPayPal.setText("Iniciar Sesion");
                        
                    }catch (Exception e) {
                        System.out.println(e);
                    }
                    
                }
            }
    }//GEN-LAST:event_btnIniciarPayPalMouseClicked

    public void recepciónInformacion(String nom, String ced, String correo, String tel, String codPal, String nomPal, String cod,int idPalco, String valor){
        this.nombre = nom;
        this.cedula = ced;
        this.email = correo;
        this.telefono = tel;
        this.codigoPalco = codPal;
        this.nombrePalco = nomPal;
        this.codigo = cod;
        this.idPalco = idPalco;
        this.valor = valor;
        txtValor.setText(valor);
    }
    
    public void recepcionInformacionZonas(String nom, String ced, String correo, String tel, String zona, String codigo){
        this.nombre = nom;
        this.cedula = ced;
        this.email = correo;
        this.telefono = tel;
        this.zona = zona;
        this.codigo = codigo;
        this.valor = "800.000";
        
        this.tipoCompra = 2;
    }

    Pattern pattern = Pattern
                .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
 
        // El email a validar
    
        public boolean validarCorreo(String email){
            Matcher mather = pattern.matcher(email);
            if (mather.find() == true) {
                return true;
            } else {
                return false;
            }           
        }
    
    public boolean validarCampos(){
        if(txtCorreoPayPal.getText().length()==0 || txtContraseñaPayPal.getText().length()==0)
            return false;
        else return true;  
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarPayPal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtContraseñaPayPal;
    private javax.swing.JTextField txtCorreoPayPal;
    private javax.swing.JLabel txtValor;
    // End of variables declaration//GEN-END:variables
}
