/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.BorderLayout;
import java.sql.Connection;
import javax.swing.JPanel;

/**
 *
 * @author leang
 */
public class PasarelaPagos extends javax.swing.JFrame {

    /**
     * Creates new form PasarelaPagos
     */    
    
    public PasarelaPagos() {
        initComponents();
    }
    
    public String nombre;
    public String cedula;
    public String email;
    public String telefono;
    
    
    
    public String codigoPalco;
    public String nombrePalco;
    
    public int idPalco;
    public String valor;
    
    public String codigo;
    public int tipoCompra;
    
    public String zona;
    
    
    public void recepciónInformacion(String nom, String ced, String correo, String tel, String codPal, String nomPal, String cod,int idPalco){
       
        this.nombre = nom;
        this.cedula = ced;
        this.email = correo;
        this.telefono = tel;
        this.codigoPalco = codPal;
        this.nombrePalco = nomPal;
        this.codigo = cod;
        this.idPalco = idPalco;
        txtClienteInfo.setText(nom+"  C. C: "+ced);
        
        if(nomPal.equals("Dakiti")) {
            this.valor = "5'000.000";
        }
        if(nomPal.equals("Yonaguni")){
            this.valor = "6'200.000";
        }
        if(nomPal.equals("Callaita")){
            this.valor = "4'300.000";
        }
        if(nomPal.equals("Oasis")){
            this.valor = "3'500.000";    
        }
        
        txtClienteValor.setText(nomPal+" Valor compra: $"+this.valor);
        this.tipoCompra = 1;
    }
    
    public void recepcionInformacionZonas(String nom, String ced, String correo, String tel, String zona, String codigo){
        this.nombre = nom;
        this.cedula = ced;
        this.email = correo;
        this.telefono = tel;
        this.zona = zona;
        this.codigo = codigo;
        this.valor = "800.000";
        
        this.tipoCompra = 2;
        txtClienteInfo.setText(nom+"  C. C: "+ced);
        txtClienteValor.setText("Valor compra: $"+this.valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtClienteInfo = new javax.swing.JLabel();
        txtClienteValor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        contentPagos = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pagos2.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pagos2.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        txtClienteInfo.setText("Nombre cliente y cedula");

        txtClienteValor.setText("Palco a comprar y valor");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel5.setText("RoyalTicket");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtClienteValor, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClienteInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClienteInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtClienteValor)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 120));

        contentPagos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPagosLayout = new javax.swing.GroupLayout(contentPagos);
        contentPagos.setLayout(contentPagosLayout);
        contentPagosLayout.setHorizontalGroup(
            contentPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        contentPagosLayout.setVerticalGroup(
            contentPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        jPanel2.add(contentPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 360, 260));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paypal.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 100, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnVisa.png"))); // NOI18N
        jLabel13.setText("jLabel12");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnMaster.jpg"))); // NOI18N
        jLabel14.setText("jLabel12");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        PasarelaVisa visa = new PasarelaVisa();
        if(this.tipoCompra==1)visa.recepciónInformacion(nombre, cedula, codigo, cedula, codigoPalco, nombrePalco, codigo,idPalco);
        else visa.recepcionInformacionZonas(nombre, cedula,email, telefono, zona, codigo);
        ShowPanel(visa);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        PasarelaMasterCard master = new PasarelaMasterCard();   
        if(this.tipoCompra==1)master.recepciónInformacion(nombre, cedula, codigo, cedula, codigoPalco, nombrePalco, codigo,idPalco);
        else master.recepcionInformacionZonas(nombre, cedula,email, telefono, zona, codigo);
        ShowPanel(master);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        PasarelaPayPal pay = new PasarelaPayPal();
        if(this.tipoCompra==1)pay.recepciónInformacion(nombre, cedula, codigo, cedula, codigoPalco, nombrePalco, codigo,idPalco, this.valor);
        else pay.recepcionInformacionZonas(nombre, cedula,email, telefono, zona, codigo);
        ShowPanel(pay);
        
        
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasarelaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasarelaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasarelaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasarelaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasarelaPagos().setVisible(true);
            }
        });*/
    }
    
    public void cerrarVentana(){
        this.dispose();
    }
    
    private void ShowPanel(JPanel p){
        p.setSize(680,400);
        p.setLocation(0,0);
        
        contentPagos.removeAll();
        contentPagos.add(p,BorderLayout.CENTER);
        contentPagos.revalidate();
        contentPagos.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPagos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtClienteInfo;
    private javax.swing.JLabel txtClienteValor;
    // End of variables declaration//GEN-END:variables
}
