/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author leang
 */
public class PasarelaVisa extends javax.swing.JPanel {

    public String nombre;
    public String cedula;
    public String email;
    public String telefono;
    
    
    public String codigoPalco;
    public String nombrePalco;
    public int idPalco;
    
    public String codigo;
    public String valor;
    public int tipoCompra;
    
    public String zona;
    
    Connection con = null;
    PreparedStatement pst2 = null;
    PreparedStatement pst3 = null;
    
    
    public PasarelaVisa() {
        initComponents();
        //con = DbConnection.ConnectionDB();
    }

    public void recepciónInformacion(String nom, String ced, String correo, String tel, String codPal, String nomPal, String cod,int idPalco){
        this.nombre = nom;
        this.cedula = ced;
        this.email = correo;
        this.telefono = tel;
        this.codigoPalco = codPal;
        this.nombrePalco = nomPal;
        this.codigo = cod;
        this.idPalco = idPalco;
    }
    
    public void recepcionInformacionZonas(String nom, String ced, String correo, String tel, String zona, String codigo){
        this.nombre = nom;
        this.cedula = ced;
        this.email = correo;
        this.telefono = tel;
        this.zona = zona;
        this.codigo = codigo;
        this.valor = "800.000";
        
        this.tipoCompra = 2;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtCorreoVisa = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtTarjetaVisa = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtMesTarjeta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAñoTarjeta = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtCVC = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/email.png"))); // NOI18N

        txtCorreoVisa.setText("Example@gmail.com");
        txtCorreoVisa.setBorder(null);
        txtCorreoVisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoVisaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreoVisa, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtCorreoVisa)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/visa.png"))); // NOI18N

        txtTarjetaVisa.setText("Número de tárjeta");
        txtTarjetaVisa.setBorder(null);
        txtTarjetaVisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTarjetaVisaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTarjetaVisa, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtTarjetaVisa)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 260, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendar.png"))); // NOI18N

        txtMesTarjeta.setText("MM ");
        txtMesTarjeta.setBorder(null);
        txtMesTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMesTarjetaMousePressed(evt);
            }
        });
        txtMesTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesTarjetaActionPerformed(evt);
            }
        });

        jLabel1.setText("/");

        txtAñoTarjeta.setText("YY");
        txtAñoTarjeta.setBorder(null);
        txtAñoTarjeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtAñoTarjetaMousePressed(evt);
            }
        });
        txtAñoTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAñoTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMesTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(txtAñoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMesTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtAñoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/candado.png"))); // NOI18N

        txtCVC.setText("CVC");
        txtCVC.setBorder(null);
        txtCVC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCVCMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCVC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtCVC)
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 130, -1));

        btnPagar.setBackground(new java.awt.Color(204, 255, 255));
        btnPagar.setText("PAGAR");
        btnPagar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel2.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMesTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesTarjetaActionPerformed

    private void txtAñoTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñoTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoTarjetaActionPerformed

        Pattern pattern = Pattern
                .compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
 
        // El email a validar
    
        public boolean validarCorreo(String email){
            Matcher mather = pattern.matcher(email);
            if (mather.find() == true) {
                return true;
            } else {
                return false;
            }           
        }
    
    public boolean validarCampos(){
        if(txtCorreoVisa.getText().length()==0 || txtTarjetaVisa.getText().length()==0 ||
                txtMesTarjeta.getText().length()==0 || txtAñoTarjeta.getText().length()==0 || txtCVC.getText().length()==0)
            return false;
        else return true;  
    }
    
    
    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        
        if(this.tipoCompra==1){
            String sql2 = "INSERT INTO entradasPalcos (nombre,cedula,email,telefono,codigoPalco,nombrePalco,codigo) VALUES (?,?,?,?,?,?,?);";
            String codigo;
            ComprarPalco cp = new ComprarPalco();
            try{
                if(!validarCampos()) JOptionPane.showMessageDialog(null, "Llene todos los campos.");
            
                else{
                    if(!validarCorreo(txtCorreoVisa.getText()))
                        JOptionPane.showMessageDialog(null, "Correo no válido");
                    else{
                        pst2 = con.prepareStatement(sql2);
                        pst2.setString(1, this.nombre);
                        pst2.setString(2, this.cedula);
                        pst2.setString(3, this.email);
                        pst2.setString(4, this.telefono);
                        pst2.setString(5, this.codigoPalco);
                        pst2.setString(6, this.nombrePalco);
                        pst2.setString(7, this.codigo);
                        
                        pst2.execute();          

                        JOptionPane.showMessageDialog(null, "Compra Exitosa, Su codigo de reserva es: "+this.codigo+" para palco "+this.nombrePalco+" "+this.codigoPalco);
                        String sql3="UPDATE palcos SET disponibilidad='Ocupado' WHERE id='"+this.idPalco+"'";
                        pst3 = con.prepareStatement(sql3);
                        int rs2= pst3.executeUpdate(); 
                        if(rs2>0){
                            System.out.println("Disponibilidad modificada");            
                        }else{
                            System.out.println("No modificado");
                        }
                  
                //con.close();
                    }
                }
            }catch(Exception e){
                System.out.println("Codigo de palco incorrecto o no disponible. "+e);
            }
        }
        if(this.tipoCompra==2){
            
            try{
                String sql = "INSERT INTO entradaBasica (cedula, telefono, email, nombre, zona, codigo) VALUES (?,?,?,?,?,?);";
                pst2 = con.prepareStatement(sql);
                pst2.setString(1, this.cedula);
                pst2.setString(3, this.email);
                pst2.setString(2, this.telefono);
                pst2.setString(4, this.nombre);
                pst2.setString(5, this.zona);
                pst2.setString(6, this.codigo);
                pst2.execute();
                JOptionPane.showMessageDialog(null, "Compra Exitosa, Su codigo de reserva es: "+this.codigo);
            }catch(Exception e){
                System.out.println("Error");
            }
        }
        
       
    }//GEN-LAST:event_btnPagarActionPerformed

    private void txtCorreoVisaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoVisaMousePressed
        txtCorreoVisa.setText("");
    }//GEN-LAST:event_txtCorreoVisaMousePressed

    private void txtTarjetaVisaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTarjetaVisaMousePressed
        txtTarjetaVisa.setText("");
    }//GEN-LAST:event_txtTarjetaVisaMousePressed

    private void txtMesTarjetaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMesTarjetaMousePressed
        txtMesTarjeta.setText("");
    }//GEN-LAST:event_txtMesTarjetaMousePressed

    private void txtAñoTarjetaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAñoTarjetaMousePressed
        txtAñoTarjeta.setText("");
    }//GEN-LAST:event_txtAñoTarjetaMousePressed

    private void txtCVCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCVCMousePressed
        txtCVC.setText("");
    }//GEN-LAST:event_txtCVCMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtAñoTarjeta;
    private javax.swing.JTextField txtCVC;
    private javax.swing.JTextField txtCorreoVisa;
    private javax.swing.JTextField txtMesTarjeta;
    private javax.swing.JTextField txtTarjetaVisa;
    // End of variables declaration//GEN-END:variables
}
