/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author leang
 */
public class PayPal extends javax.swing.JFrame {

    /**
     * Creates new form PayPal
     */
    public Connection con = null;
    ComprarPalco menu = new ComprarPalco();
    
    public PayPal() {
        initComponents();
        /*
        try{
            menu.con.close();
        }catch(Exception e){
            System.out.println("Errorcito");
        }*/
        con = DbConnection.ConnectionDB();
    }
    
    public String nombre;
    public String cedula;
    public String email;
    public String telefono;
    public String codigoPalco;
    public String nombrePalco;
    public String codigo;
    public String valor;
    public int idPalco;
    
    //Connection con = null;
    PreparedStatement pst2 = null;
    PreparedStatement pst3 = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JLabel();
        txtSaludo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JLabel();
        btnIniciarPayPal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paypal2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 310, 10));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 20, -1));

        txtValor.setText("Valor");
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 120, -1));

        txtSaludo.setText("Hola de nuevo ...");
        jPanel1.add(txtSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Cambiar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Enviar a");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, 30));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("COP");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 40, -1));

        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("¿No eres tú?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 63, 310, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Pagar con");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 140, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pay pqueño.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("RoyalTicket");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Cambiar");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Saldo PayPal");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 130, -1));

        txtValor2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtValor2.setText("valor");
        jPanel1.add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 120, -1));

        btnIniciarPayPal.setBackground(new java.awt.Color(51, 153, 255));
        btnIniciarPayPal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIniciarPayPal.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarPayPal.setText("Pagar Ahora");
        btnIniciarPayPal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarPayPalMouseClicked(evt);
            }
        });
        jPanel1.add(btnIniciarPayPal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarPayPalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarPayPalMouseClicked

        String sql2 = "INSERT INTO entradasPalcos (nombre,cedula,email,telefono,codigoPalco,nombrePalco,codigo) VALUES (?,?,?,?,?,?,?);";
        String codigo;
        ComprarPalco cp = new ComprarPalco();
        PasarelaPagos pasarela = new PasarelaPagos();
        
        try{
            
            pst2 = con.prepareStatement(sql2);
            pst2.setString(1, this.nombre);
            pst2.setString(2, this.cedula);
            pst2.setString(3, this.email);
            pst2.setString(4, this.telefono);
            pst2.setString(5, this.codigoPalco);
            pst2.setString(6, this.nombrePalco);
            pst2.setString(7, this.codigo);
                       
            pst2.execute();          

            JOptionPane.showMessageDialog(null, "Compra Exitosa, Su codigo de reserva es: "+this.codigo+" para palco "+this.nombrePalco+" "+this.codigoPalco);
            String sql3="UPDATE palcos SET disponibilidad='Ocupado' WHERE id='"+this.idPalco+"'";
            pst3 = con.prepareStatement(sql3);
            int rs2= pst3.executeUpdate(); 
            if(rs2>0){
                System.out.println("Disponibilidad modificada");          
                this.dispose();
                pasarela.cerrarVentana();
                con.close();
                menu.generarConexion();
                menu.limpiarCampos();
             }else{
                System.out.println("No modificado");
             }
                  
             
                
            
        }catch(Exception e){
            System.out.println("Codigo de palco incorrecto o no disponible. "+e);
        }
        
    }//GEN-LAST:event_btnIniciarPayPalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayPal().setVisible(true);
            }
        });*/
    }
    
    
    public void recepciónInformacion(String nom, String ced, String correo, String tel, String codPal, String nomPal, String cod,int idPalco,String valor){
        this.nombre = nom;
        this.cedula = ced;
        this.email = correo;
        this.telefono = tel;
        this.codigoPalco = codPal;
        this.nombrePalco = nomPal;
        this.codigo = cod;
        this.valor = valor;
        this.idPalco = idPalco;
        
        txtValor.setText("$ "+valor);
        txtSaludo.setText("Hola de nuevo "+nombre);
        txtValor2.setText("$ "+valor);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarPayPal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel txtSaludo;
    private javax.swing.JLabel txtValor;
    private javax.swing.JLabel txtValor2;
    // End of variables declaration//GEN-END:variables
}
